apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-secret
# type Opaque by default for arbitarary key-value pairs
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=